import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Search, MapPin, SlidersHorizontal, Sparkles, Building2, Clock3, BriefcaseBusiness, ChevronLeft, ChevronRight, Check, X, CircleHelp } from 'lucide-react';
import { api } from '../../lib/api';
import { useAuth } from '../../context/AuthContext';
import { Badge, Button, EmptyState, ErrorState, Spinner } from '../../components/ui';
import { idOf, initials, relativeDate, salary } from '../../lib/utils';

export function CompanyLogo({ company, index = 0 }) {
  const [failed, setFailed] = useState(false);
  const name = company?.name || 'Company';
  return <div className={`company-logo logo-${index % 5}`}>{company?.logo && !failed ? <img src={typeof company.logo === 'string' ? company.logo : company.logo.url} alt={`${name} logo`} onError={() => setFailed(true)} /> : initials(name)}</div>;
}
export default function Jobs() {
  const { user } = useAuth();
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState(params.get('q') || '');
  const [location, setLocation] = useState(params.get('location') || '');
  const [result, setResult] = useState({ jobs: [], total: 0, pages: 1 });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [reload, setReload] = useState(0);
  const [showFilters, setShowFilters] = useState(false);
  const [profile, setProfile] = useState(null);
  const queryString = params.toString();
  const filterCount = ['jobType', 'experienceLevel', 'salaryMin'].filter((key) => params.has(key)).length;
  function update(key, value) { setParams((current) => { const next = new URLSearchParams(current); value ? next.set(key, value) : next.delete(key); if (key !== 'page') next.delete('page'); return next; }); }
  useEffect(() => { const timer = setTimeout(() => { setParams((current) => { const next = new URLSearchParams(current); const changed = (next.get('q') || '') !== search || (next.get('location') || '') !== location; if (!changed) return current; search ? next.set('q', search) : next.delete('q'); location ? next.set('location', location) : next.delete('location'); next.delete('page'); return next; }, { replace: true }); }, 350); return () => clearTimeout(timer); }, [search, location, setParams]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); api.get(`/jobs?${queryString}`, { signal: controller.signal }).then(setResult).catch((err) => { if (err.name !== 'AbortError') setError(err.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [queryString, reload, user]);
  useEffect(() => { if (user?.role !== 'seeker') return; let active = true; api.get('/profile').then((data) => { if (active) setProfile(data); }).catch(() => {}); return () => { active = false; }; }, [user]);
  const profileSteps = [{ label: 'Your introduction', done: Boolean(profile?.summary) }, { label: 'Skills & experience', done: Boolean(profile?.skills?.length && profile?.experience?.length) }, { label: 'Upload your resume', done: Boolean(profile?.resume?.originalName) }];
  const completed = profileSteps.filter((step) => step.done).length;
  function clearFilters() { setSearch(''); setLocation(''); setParams({}); }
  return <div className="page-stack jobs-page">
    <div className="page-header"><div><div className="eyebrow">THE RIGHT ROLE IS OUT THERE</div><h1>{user ? `Let’s find your next move, ${user.name.split(' ')[0]}.` : 'Find your next great opportunity.'}</h1><p className="muted mt-2">Good work starts with the right fit. Explore what’s next.</p></div><span className="heading-label"><span className="live-dot" />Open to possibilities</span></div>
    <div className="search-bar"><label className="search-keyword"><Search size={21} /><span className="sr-only">Job title, company, or skill</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Job title, company, or skill" /></label><label className="search-location"><MapPin size={20} /><span className="sr-only">Location</span><input value={location} onChange={(e) => setLocation(e.target.value)} placeholder="City or region" /></label><Button onClick={() => setReload((value) => value + 1)}>Find opportunities</Button></div>
    <div className="opportunity-banner"><div className="banner-icon"><Sparkles size={25} /></div><div><h2>Your skills. A world of possibilities.</h2><p>{user ? 'Keep your profile up to date to see how your skills match each role.' : 'Create your profile to see your skills match and apply in one click.'}</p></div><Link to={user ? '/seeker/profile' : '/auth/seeker/register'} className="btn btn-secondary">{user ? 'Update profile' : 'Create your profile'}</Link></div>
    <div className="jobs-workspace"><aside className={`filter-panel ${showFilters ? 'filters-visible' : ''}`}><div className="filter-heading"><h2><SlidersHorizontal size={18} />Filters</h2><button onClick={clearFilters}>Reset</button></div><FilterGroup title="Workplace" options={['Remote', 'Hybrid', 'Onsite']} value={params.get('jobType')} onChange={(value) => update('jobType', value)} /><FilterGroup title="Experience level" options={['Entry', 'Mid', 'Senior', 'Lead']} value={params.get('experienceLevel')} onChange={(value) => update('experienceLevel', value)} /><div className="filter-group"><h3>Minimum annual salary</h3><label className="sr-only" htmlFor="salary-filter">Minimum salary in USD</label><select id="salary-filter" value={params.get('salaryMin') || ''} onChange={(e) => update('salaryMin', e.target.value)}><option value="">Any salary</option value="40000">$40,000+</option value="60000">$60,000+</option value="80000">$80,000+</option value="100000">$100,000+</option value="150000">$150,000+</option></select><p className="field-hint mt-2">Annual salary, shown in USD.</p></div><div className="filter-footnote"><CircleHelp size={17} /><p>A match score compares your saved skills with the skills in a job. It’s a guide, not a hiring prediction.</p></div></aside>
    <section className="job-results" aria-label="Job search results"><div className="results-toolbar"><div><h2>Explore opportunities <span className="count-chip">{result.total}</span></h2><p className="muted text-sm mt-1">Find a place to do your best work.</p></div><div className="flex gap-2 items-center"><button className="icon-button filter-toggle" onClick={() => setShowFilters(!showFilters)} aria-label="Toggle filters" aria-expanded={showFilters}><SlidersHorizontal size={20} /></button><label className="sort-label"><span>Sort by</span><select aria-label="Sort jobs" value={params.get('sort') || 'newest'} onChange={(e) => update('sort', e.target.value)}><option value="newest">Newest</option><option value="salary">Highest salary</option>{user && <option value="match">Best match</option>}</select></label></div></div>{filterCount > 0 && <div className="active-filters">{['jobType', 'experienceLevel', 'salaryMin'].map((key) => params.get(key) && <button key={key} onClick={() => update(key, '')}>{key === 'salaryMin' ? `$${Number(params.get(key)).toLocaleString()}+` : params.get(key)}<X size={13} /></button>)}</div>}
      {loading ? <Spinner /> : error ? <ErrorState message={error} onRetry={() => setReload((value) => value + 1)} /> : !result.jobs?.length ? <EmptyState icon={Search} title="A fresh search might do it." description="Try a different keyword or broaden your filters to find more opportunities." action={<Button variant="secondary" onClick={clearFilters}>Clear filters</Button>} /> : <><div className="job-list">{result.jobs.map((job, index) => <JobCard key={idOf(job)} job={job} index={index} showMatch={Boolean(user)} />)}</div><div className="pagination"><span>Page {result.page || 1} of {result.pages || 1}</span><div className="flex gap-2"><Button variant="secondary" disabled={(result.page || 1) <= 1} onClick={() => update('page', String((result.page || 1) - 1))}><ChevronLeft size={17} />Previous</Button><Button variant="secondary" disabled={(result.page || 1) >= (result.pages || 1)} onClick={() => update('page', String((result.page || 1) + 1))}>Next<ChevronRight size={17} /></Button></div></div></>}
    </section><aside className="jobs-right-rail"><div className="profile-progress-card"><div className="flex justify-between items-center"><span className="eyebrow">YOUR PROFILE</span><span className="progress-count">{user ? `${Math.round(completed / 3 * 100)}%` : 'Get started'}</span></div><h3>A strong profile<br />opens more doors.</h3><div className="progress-track"><span style={{ width: `${completed / 3 * 100}%` }} /></div><div className="profile-checklist">{profileSteps.map((step) => <div key={step.label} className={step.done ? 'complete' : ''}><span>{step.done ? <Check size={12} /> : ''}</span>{step.label}</div>)}</div><Link to={user ? '/seeker/profile' : '/auth/seeker/register'} className="btn btn-secondary w-full">{user ? 'Complete profile' : 'Join Hirelane'}</Link></div><div className="career-note"><span className="eyebrow">A SMALL REMINDER</span><p>You don’t have to check every box to be a great fit.</p><span>Take the next step. Apply.</span></div></aside></div>
  </div>;
}
function FilterGroup({ title, options, value, onChange }) { return <fieldset className="filter-group"><legend>{title}</legend>{options.map((option) => <label className="filter-option" key={option}><input type="checkbox" checked={value === option} onChange={() => onChange(value === option ? '' : option)} /><span>{option === 'Entry' ? 'Entry level' : option === 'Mid' ? 'Mid level' : option}</span></label>)}</fieldset>; }
export function JobCard({ job, index, showMatch }) { return <article className="job-card"><div className="job-card-top"><CompanyLogo company={job.company} index={index} /><div className="job-card-title"><div className="company-name">{job.company?.name || 'Company'}</div><Link to={`/jobs/${idOf(job)}`}><h3>{job.title}</h3></Link></div>{showMatch && typeof job.matchScore === 'number' && <span className="match-score" title="Percentage of required skills found in your profile"><Sparkles size={14} />{job.matchScore}% match</span>}</div><div className="job-meta"><span><MapPin size={15} />{job.location || 'Anywhere'}</span><span><BriefcaseBusiness size={15} />{job.employmentType || 'Full-time'}</span><span><Building2 size={15} />{job.jobType}</span></div><div className="job-skills">{job.skills?.slice(0, 4).map((skill) => <Badge key={skill}>{skill}</Badge>)}{job.skills?.length > 4 && <Badge>+{job.skills.length - 4}</Badge>}</div><div className="job-card-bottom"><div><strong>{salary(job)}</strong><span className="muted"> / year</span></div><span className="posted-date"><Clock3 size={14} />{relativeDate(job.createdAt)}</span><Link className="job-view" to={`/jobs/${idOf(job)}`}>View opportunity<ChevronRight size={16} /></Link></div></article>; }
