import { useEffect, useRef, useState } from 'react';
import { FileText, UploadCloud, Plus, Trash2, Save, LoaderCircle, Download, UserRound, BriefcaseBusiness, GraduationCap } from 'lucide-react';
import { api } from '../../lib/api';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import { Button, Field, PageHeader, Spinner, ErrorState, Badge } from '../../components/ui';
import { initials } from '../../lib/utils';
const blank = { headline: '', location: '', summary: '', skills: [], experience: [], education: [] };

export default function Profile() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [profile, setProfile] = useState(null);
  const [skills, setSkills] = useState('');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [retry, setRetry] = useState(0);
  const [dirty, setDirty] = useState(false);
  const fileInput = useRef(null);
  useEffect(() => { let active = true; setError(''); api.get('/profile').then((data) => { if (active) { setProfile({ ...blank, ...data }); setSkills((data.skills || []).join(', ')); } }).catch((err) => { if (active) setError(err.message); }); return () => { active = false; }; }, [retry]);
  useEffect(() => { if (!dirty) return; const warn = (event) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  function change(field, value) { setProfile((current) => ({ ...current, [field]: value })); setDirty(true); }
  function updateEntry(section, index, field, value) { change(section, profile[section].map((entry, position) => position === index ? { ...entry, [field]: value } : entry)); }
  async function save(event) { event.preventDefault(); setSaving(true); try { const { headline, location, summary, experience, education } = profile; const result = await api.put('/profile', { headline, location, summary, experience, education, skills: [...new Set(skills.split(',').map((skill) => skill.trim()).filter(Boolean))] }); setProfile({ ...blank, ...result }); setSkills((result.skills || []).join(', ')); setDirty(false); toast('Your profile is up to date.'); } catch (err) { toast(err.message, 'error'); } finally { setSaving(false); } }
  async function upload(file) {
    if (!file) return;
    if (!/\.(pdf|docx)$/i.test(file.name)) return toast('Please choose a PDF or DOCX resume.', 'error');
    if (file.size > 5 * 1024 * 1024) return toast('Your resume must be smaller than 5 MB.', 'error');
    setUploading(true);
    try { const result = await api.upload('/profile/resume', file); const uploaded = result.profile || result; setProfile((current) => ({ ...current, resume: uploaded.resume })); const merged = [...new Set([...skills.split(',').map((value) => value.trim()).filter(Boolean), ...(uploaded.skills || [])])]; setSkills(merged.join(', ')); setDirty(true); toast('Resume uploaded. Review the extracted skills and save your profile.'); }
    catch (err) { toast(err.message, 'error'); } finally { setUploading(false); if (fileInput.current) fileInput.current.value = ''; }
  }
  async function download() { try { const result = await api.get('/profile/resume/download'); window.location.assign(result.url); } catch (err) { toast(err.message, 'error'); } }
  if (error) return <ErrorState message={error} onRetry={() => setRetry((value) => value + 1)} />;
  if (!profile) return <Spinner />;
  return <form onSubmit={save} className="page-stack"><PageHeader eyebrow="YOUR STORY, YOUR WAY" title="Make a great first impression." description="Give employers a clear picture of what you bring to the team." actions={<Button type="submit" disabled={saving || uploading}>{saving ? <LoaderCircle size={17} className="animate-spin" /> : <Save size={17} />}{saving ? 'Saving…' : 'Save profile'}</Button>} /><div className="profile-layout"><div className="page-stack"><section className="card profile-section"><div className="section-heading"><UserRound size={20} /><h2>The introduction</h2></div><div className="profile-identity"><div className="avatar avatar-large">{initials(user.name)}</div><div><h3>{user.name}</h3><p className="muted">{user.email}</p></div><Badge tone="green">Job seeker</Badge></div><div className="form-grid"><Field label="Professional headline"><input value={profile.headline} onChange={(e) => change('headline', e.target.value)} maxLength={150} placeholder="Full-stack engineer · React & Node.js" /></Field><Field label="Location"><input value={profile.location} onChange={(e) => change('location', e.target.value)} maxLength={160} placeholder="Bengaluru, India" /></Field><div className="full-width"><Field label="About you" hint="A few lines about your experience, strengths, and what you’re looking for."><textarea rows={5} maxLength={5000} value={profile.summary} onChange={(e) => change('summary', e.target.value)} placeholder="Tell your story…" /></Field></div><div className="full-width"><Field label="Your skills" hint="Separate skills with commas. These power your job match scores."><input value={skills} maxLength={4000} onChange={(e) => { setSkills(e.target.value); setDirty(true); }} placeholder="React, JavaScript, Node.js, MongoDB" /></Field><div className="flex flex-wrap gap-2 mt-3">{skills.split(',').map((skill) => skill.trim()).filter(Boolean).slice(0, 16).map((skill, index) => <Badge tone="green" key={`${skill}-${index}`}>{skill}</Badge>)}</div></div></div></section>
    <section className="card profile-section"><div className="section-heading justify-between"><div className="flex items-center gap-2"><BriefcaseBusiness size={20} /><h2>Work experience</h2></div><Button variant="ghost" disabled={profile.experience.length >= 20} onClick={() => change('experience', [...profile.experience, { title: '', company: '', startDate: '', endDate: '', description: '' }])}><Plus size={16} />Add experience</Button></div>{!profile.experience.length && <p className="muted py-5">Your experience belongs here. Add a role, an internship, or a project.</p>}{profile.experience.map((entry, index) => <div className="repeatable-entry" key={index}><div className="flex justify-between items-center mb-4"><h3>Experience {index + 1}</h3><button type="button" className="icon-button text-red-600" aria-label={`Remove experience ${index + 1}`} onClick={() => change('experience', profile.experience.filter((_, i) => i !== index))}><Trash2 size={17} /></button></div><div className="form-grid"><Field label="Job title"><input required maxLength={150} value={entry.title} onChange={(e) => updateEntry('experience', index, 'title', e.target.value)} /></Field><Field label="Company"><input required maxLength={150} value={entry.company} onChange={(e) => updateEntry('experience', index, 'company', e.target.value)} /></Field><Field label="Start date"><input type="date" value={entry.startDate} onChange={(e) => updateEntry('experience', index, 'startDate', e.target.value)} /></Field><Field label="End date" hint="Leave empty if you currently work here."><input type="date" min={entry.startDate || undefined} value={entry.endDate} onChange={(e) => updateEntry('experience', index, 'endDate', e.target.value)} /></Field><div className="full-width"><Field label="Highlights"><textarea rows={3} maxLength={3000} value={entry.description} onChange={(e) => updateEntry('experience', index, 'description', e.target.value)} placeholder="What did you work on? What changed because of your work?" /></Field></div></div></div>)}</section>
    <section className="card profile-section"><div className="section-heading justify-between"><div className="flex items-center gap-2"><GraduationCap size={20} /><h2>Education</h2></div><Button variant="ghost" disabled={profile.education.length >= 20} onClick={() => change('education', [...profile.education, { school: '', degree: '', startDate: '', endDate: '' }])}><Plus size={16} />Add education</Button></div>{!profile.education.length && <p className="muted py-5">Add your school, degree, or a relevant program.</p>}{profile.education.map((entry, index) => <div className="repeatable-entry" key={index}><div className="flex justify-between items-center mb-4"><h3>Education {index + 1}</h3><button type="button" className="icon-button text-red-600" aria-label={`Remove education ${index + 1}`} onClick={() => change('education', profile.education.filter((_, i) => i !== index))}><Trash2 size={17} /></button></div><div className="form-grid"><Field label="School or university"><input required maxLength={200} value={entry.school} onChange={(e) => updateEntry('education', index, 'school', e.target.value)} /></Field><Field label="Degree or program"><input required maxLength={200} value={entry.degree} onChange={(e) => updateEntry('education', index, 'degree', e.target.value)} /></Field><Field label="Start date"><input type="date" value={entry.startDate} onChange={(e) => updateEntry('education', index, 'startDate', e.target.value)} /></Field><Field label="End date"><input type="date" min={entry.startDate || undefined} value={entry.endDate} onChange={(e) => updateEntry('education', index, 'endDate', e.target.value)} /></Field></div></div>)}</section></div>
    <aside className="page-stack self-start"><section className="card resume-card"><div className="section-heading"><FileText size={20} /><h2>Your resume</h2></div><p className="muted text-sm mt-3">Upload once. Apply with confidence.</p><button type="button" className="upload-zone" disabled={uploading || saving} onClick={() => fileInput.current?.click()}>{uploading ? <LoaderCircle size={30} className="animate-spin" /> : <UploadCloud size={30} />}<strong>{uploading ? 'Reading your resume…' : profile.resume ? 'Replace resume' : 'Upload your resume'}</strong><span>PDF or DOCX · Up to 5 MB</span></button><input className="sr-only" aria-label="Upload resume" type="file" accept=".pdf,.docx" ref={fileInput} onChange={(e) => upload(e.target.files?.[0])} disabled={uploading} />{profile.resume?.originalName && <div className="resume-file"><FileText size={23} /><div className="min-w-0 flex-1"><strong className="block truncate">{profile.resume.originalName}</strong><span>Ready for your next application</span></div><button type="button" className="icon-button" aria-label="Download saved resume" onClick={download}><Download size={18} /></button></div>}<p className="field-hint mt-4">We extract recognizable skills from text-based resumes. Review the suggestions before saving. Scanned PDFs may need a text-based version.</p></section><div className="profile-tip"><span className="eyebrow">A PROFILE THAT SOUNDS LIKE YOU</span><p>Be specific about your skills and the impact you’ve made. A few clear examples go a long way.</p></div>{dirty && <p className="text-sm text-amber-700">You have unsaved profile changes.</p>}</aside></div><div className="flex justify-end"><Button type="submit" disabled={saving || uploading}><Save size={17} />Save profile</Button></div></form>;
}
