import { Router } from 'express';
import multer from 'multer';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { authLimiter, uploadLimiter, aiLimiter } from '../middleware/security.js';
import { validate, objectId } from '../middleware/validate.js';
import * as schemas from '../validation/schemas.js';
import * as auth from '../controllers/authController.js';
import * as profile from '../controllers/profileController.js';
import * as company from '../controllers/companyController.js';
import * as jobs from '../controllers/jobController.js';
import * as applications from '../controllers/applicationController.js';
import { generateDescription } from '../controllers/aiController.js';

export const router = Router();
router.param('id', objectId);
const seeker = requireRole('seeker');
const employer = requireRole('employer');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024, files: 1, fields: 5, parts: 6 } }).single('file');

router.post('/auth/register', authLimiter, validate(schemas.registerSchema), auth.register);
router.post('/auth/login', authLimiter, validate(schemas.loginSchema), auth.login);
router.post('/auth/logout', auth.logout);
router.get('/auth/me', requireAuth, auth.me);
router.get('/profile', seeker, profile.getProfile);
router.put('/profile', seeker, validate(schemas.profileSchema), profile.updateProfile);
router.post('/profile/resume', seeker, uploadLimiter, upload, profile.uploadResume);
router.get('/profile/resume/download', seeker, profile.downloadResume);
router.get('/company', employer, company.getCompany);
router.put('/company', employer, validate(schemas.companySchema), company.updateCompany);
router.post('/company/logo', employer, uploadLimiter, upload, company.uploadLogo);
router.get('/jobs', validate(schemas.searchSchema, 'query'), jobs.listJobs);
router.get('/jobs/:id', jobs.getJob);
router.post('/jobs', employer, validate(schemas.jobSchema), jobs.createJob);
router.patch('/jobs/:id', employer, validate(schemas.jobPatchSchema), jobs.updateJob);
router.delete('/jobs/:id', employer, jobs.archiveJob);
router.get('/employer/jobs', employer, jobs.employerJobs);
router.get('/employer/applications', employer, validate(schemas.applicantQuerySchema, 'query'), applications.employerApplications);
router.post('/jobs/:id/apply', seeker, applications.apply);
router.get('/applications', seeker, applications.myApplications);
router.patch('/applications/:id/status', employer, validate(schemas.statusSchema), applications.updateStatus);
router.get('/applications/:id/resume', requireAuth, applications.downloadApplicationResume);
router.post('/ai/job-description', employer, aiLimiter, validate(schemas.aiSchema), generateDescription);
